// src/lib/components/Hero.svelte
<script>
    import { base } from "$app/paths";

    const skillCategories = [
        {
            label: "Languages",
            items: [
                { name: "Python", icon: "python.svg" },
                { name: "C++", icon: "cpp.svg" },
                { name: "C", icon: "c.svg" },
                { name: "Go", icon: "go.svg" },
                { name: "TypeScript", icon: "typescript.svg" },
                { name: "Java", icon: "java.svg" },
            ],
        },
        {
            label: "Frameworks",
            items: [
                { name: "PyTorch", icon: "pytorch.svg" },
                { name: "React", icon: "react.svg" },
                { name: "Svelte", icon: "svelte.svg" },
                { name: "Scikit-Learn", icon: "scikit-learn.svg" },
            ],
        },
        {
            label: "Other",
            items: [
                { name: "Linux", icon: "linux.svg" },
                { name: "LaTeX", icon: "latex.svg" },
            ],
        },
    ];
</script>

<div class="container hero fade-in">
    <div class="hero-columns">
        <div class="hero-left">
            <div class="intro">
                <img src="{base}/lebron.jpg" alt="Alex Kim" class="headshot" />
                <div class="intro-text">
                    <h1>Alex Kim</h1>
                    <p class="tagline">Machine Learning & Software Developer</p>
                </div>
            </div>

            <p class="bio">
                Hi, I'm Alex! I enjoy building things with data, sports, and
                math. I create full-stack applications, ML/AI solutions, and
                electronics to learn, and solve problems across diverse
                disciplines and research areas.
            </p>

            <div class="actions">
                <a href="#projects" class="btn btn-primary">View Projects</a>
                <a
                    href="{base}/resume.pdf"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="btn btn-secondary">Resume</a
                >
            </div>
        </div>

        <div class="hero-right">
            <h2>Skills</h2>
            {#each skillCategories as category}
                <div class="skills-grid">
                    {#each category.items as skill}
                        <div class="skill-item">
                            <img
                                src="{base}/icons/{skill.icon}"
                                alt={skill.name}
                                class="skill-icon"
                            />
                            <span class="skill-name">{skill.name}</span>
                        </div>
                    {/each}
                </div>
            {/each}

            <h2>Education</h2>
            <div class="edu-item">
                <img
                    src="{base}/icons/duke.png"
                    alt="Duke University"
                    class="edu-logo"
                />
                <div class="edu-text">
                    <span class="edu-degree">ECE PhD Candidate</span>
                    <span class="edu-school">Duke University (2026-2031)</span>
                </div>
            </div>
            <div class="edu-item">
                <img
                    src="{base}/icons/hamilton.png"
                    alt="Hamilton College"
                    class="edu-logo"
                />
                <div class="edu-text">
                    <span class="edu-degree"
                        >BA - Mathematics (Music minor)</span
                    >
                    <span class="edu-school">Hamilton College (2021-2025)</span>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .hero {
        padding-top: 2rem;
    }

    .hero-columns {
        display: flex;
        gap: 3rem;
        align-items: start;
    }

    .hero-left {
        flex: 1;
    }

    .hero-right {
        flex: 0 0 auto;
    }

    .hero-right h2 {
        font-size: 1.25rem;
        font-weight: 600;
        margin-bottom: 1rem;
    }

    .skills-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 0.75rem;
        margin-bottom: 0.75rem;
    }

    .skills-grid:last-of-type {
        margin-bottom: 0;
    }

    .edu-item {
        display: flex;
        align-items: center;
        gap: 0.75rem;
        padding: 0.25rem 0;
        margin-bottom: 0.25rem;
    }

    .edu-item:last-child {
        margin-bottom: 0;
    }

    .edu-logo {
        width: 36px;
        height: 36px;
        object-fit: contain;
    }

    .edu-text {
        display: flex;
        flex-direction: column;
    }

    .edu-degree {
        font-size: 0.85rem;
        font-weight: 500;
        color: var(--color-text);
    }

    .edu-school {
        font-size: 0.8rem;
        color: var(--color-text-muted);
    }

    .skill-item {
        display: flex;
        align-items: center;
        gap: 0.6rem;
        padding: 0.5rem 0.75rem;
        border: 1px solid var(--color-border);
        border-radius: 6px;
        transition: border-color 0.2s ease;
    }

    .skill-item:hover {
        border-color: #ccc;
    }

    .skill-icon {
        width: 24px;
        height: 24px;
        object-fit: contain;
    }

    .skill-name {
        font-size: 0.85rem;
        color: var(--color-text-muted);
        white-space: nowrap;
    }

    .intro {
        display: flex;
        align-items: center;
        gap: 1.5rem;
        margin-bottom: 1.5rem;
    }

    .headshot {
        width: 190px;
        height: 190px;
        border-radius: 50%;
        object-fit: cover;
        border: 2px solid var(--color-border);
    }

    .intro-text h1 {
        font-size: 2rem;
        font-weight: 600;
        margin-bottom: 0.25rem;
    }

    .tagline {
        color: var(--color-text-muted);
        font-size: 1.05rem;
    }

    .bio {
        font-size: 1.1rem;
        line-height: 1.7;
        margin-bottom: 1.5rem;
        max-width: 700px;
    }

    .actions {
        display: flex;
        gap: 1rem;
    }

    .btn {
        padding: 0.6rem 1.25rem;
        border-radius: 6px;
        font-size: 0.9rem;
        font-weight: 500;
        transition: all 0.2s ease;
    }

    .btn-primary {
        background: var(--color-text);
        color: var(--color-bg);
    }

    .btn-primary:hover {
        background: #333;
        color: var(--color-bg);
    }

    .btn-secondary {
        border: 1px solid var(--color-border);
        color: var(--color-text);
    }

    .btn-secondary:hover {
        border-color: var(--color-text);
    }

    @media (max-width: 768px) {
        .hero-columns {
            flex-direction: column;
        }

        .hero-right {
            width: 100%;
        }

        .skills-grid {
            grid-template-columns: repeat(3, 1fr);
        }
    }

    @media (max-width: 600px) {
        .intro {
            flex-direction: column;
            text-align: center;
        }

        .actions {
            flex-direction: column;
        }

        .btn {
            text-align: center;
        }

        .skills-grid {
            grid-template-columns: repeat(2, 1fr);
        }
    }
</style>

// src/components/Hero.jsx
import React from "react";
import headshot from "../assets/lebron.jpg"; // Adjust the path to your actual image location

// Assuming you have icons or image assets for each technology
import reactIcon from "../assets/react.svg";
import pytorchIcon from "../assets/pytorch.svg";
import scikitIcon from "../assets/scikit-learn.svg";
import pandasIcon from "../assets/Pandas.svg";
import postgresqlIcon from "../assets/PostgresSQL.svg";
import pythonIcon from "../assets/Python.svg";
import latexIcon from "../assets/LaTeX.svg";
import cppIcon from "../assets/C++ (CPlusPlus).svg";
import opencvIcon from "../assets/opencv.svg";
import githubIcon from "../assets/github-icon-1-logo-svgrepo-com.svg";
import linuxIcon from "../assets/linux-svgrepo-com.svg";
import dockerIcon from "../assets/docker-svgrepo-com.svg";
import tsIcon from "../assets/typescript.svg";
import cudaIcon from "../assets/cuda-svgrepo-com.svg";
import resume from "../assets/swe_resume.pdf";
import academic_cv from "../assets/CV_1_col.pdf";

const Hero = () => {
  return (
    <div className="text-white min-h-screen flex flex-col justify-center">
      <div className="max-w-7xl mx-auto px-6 py-20 mt-20">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div className="animate-slide-in-left">
            <img
              src={headshot}
              alt="Alex Kim"
              className="w-80 h-80 rounded-full mx-auto glass-morphism p-2 hover-lift"
            />
          </div>
          <div className="animate-slide-in-right space-y-6">
            <h1 className="text-5xl md:text-6xl font-bold leading-tight">
              Creative &
              <span className="bg-gradient-to-r from-cyan-300 to-blue-400 bg-clip-text text-transparent drop-shadow-lg">
                {" "}
                Interdisciplinary
              </span>
            </h1>
            <h2 className="text-2xl md:text-3xl font-light text-gray-200">
              Machine Learning & Software Solutions
            </h2>
            <p className="text-lg text-gray-300 leading-relaxed max-w-lg">
              Hi I'm Alex! I enjoy building things with data, sports, and math.
              I create full-stack applications, ML/AI solutions, and
              electronics to learn, and solve problems across diverse disciplines and research areas.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 pt-4">
              <a href={academic_cv} target="_blank" rel="noopener noreferrer">
                <button className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 px-8 py-4 rounded-xl font-semibold text-white shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105">
                  Academic CV
                </button>
              </a>
              <a href={resume} target="_blank" rel="noopener noreferrer">
                <button className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 px-8 py-4 rounded-xl font-semibold text-white shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105">
                  Resume
                </button>
              </a>
	  <a href="#projects">
                <button className="glass-morphism hover-lift px-8 py-4 rounded-xl font-semibold text-white border border-white/20 hover:bg-white/10 transition-all duration-300">
                  View Projects
                </button>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div className="w-full h-px bg-gradient-to-r from-transparent via-white/30 to-transparent my-16"></div>

      <div className="max-w-7xl mx-auto px-6 pb-20">
        <div className="text-center mb-12 animate-slide-up">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            Favorite{" "}
            <span className="bg-gradient-to-r from-cyan-300 to-blue-400 bg-clip-text text-transparent drop-shadow-lg">
              Technologies
            </span>
          </h2>
        </div>
        <div className="animate-fade-in">
          <Technologies />
        </div>
      </div>
    </div>
  );
};

const Technologies = () => {
  const technologies = [
    { name: "C++", icon: cppIcon },
    { name: "Python", icon: pythonIcon },
    { name: "TypeScript", icon: tsIcon },
    { name: "Cuda", icon: cudaIcon },
    { name: "Linux", icon: linuxIcon },
    { name: "docker", icon: dockerIcon },
    { name: "PyTorch", icon: pytorchIcon },
    { name: "OpenCV", icon: opencvIcon },
    { name: "Scikit-Learn", icon: scikitIcon },
    { name: "Pandas", icon: pandasIcon },
    { name: "React/Expo", icon: reactIcon },
    { name: "LaTeX", icon: latexIcon },
    { name: "PostgreSQL", icon: postgresqlIcon },
    { name: "Github", icon: githubIcon },
  ];

  return (
    <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-8 max-w-6xl mx-auto">
      {technologies.map((tech, index) => (
        <div
          key={index}
          className="flex flex-col items-center glass-morphism p-6 rounded-2xl tech-card-hover floating-tech group cursor-pointer"
          style={{ animationDelay: `${index * 0.1}s` }}
        >
          <div className="tech-icon-3d">
            <img
              src={tech.icon}
              alt={`${tech.name} icon`}
              className="w-16 h-16 mb-3"
            />
          </div>
          <p className="text-sm font-medium text-center text-gray-200 group-hover:text-white transition-colors duration-300">
            {tech.name}
          </p>
        </div>
      ))}
    </div>
  );
};

export default Hero;
