// src/components/Footer.jsx
import React from "react";

const Footer = () => {
  return (
    <div className="py-20">
      <div className="w-full h-px bg-gradient-to-r from-transparent via-white/30 to-transparent mb-16"></div>

      <div className="max-w-7xl mx-auto px-6">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div className="animate-slide-in-left">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
              Let's{" "}
              <span className="bg-gradient-to-r from-cyan-300 to-blue-400 bg-clip-text text-transparent drop-shadow-lg">
                Connect
              </span>
            </h2>
            <p className="text-xl text-gray-300 mb-8">
              Feel free to connect or comment about any of my work! I'm always
              open to discussing new opportunities and collaborations.
            </p>
          </div>

          <div className="animate-slide-in-right">
            <div className="glass-morphism p-8 rounded-2xl hover-lift">
              <h3 className="text-2xl font-bold text-white mb-6">
                Contact Info
              </h3>
              <div className="space-y-4">
                <a
                  href="mailto:akim42003@gmail.com"
                  className="flex items-center space-x-3 text-gray-300 hover:text-blue-400 transition-colors duration-300 group"
                >
                  <svg
                    className="w-5 h-5 group-hover:scale-110 transition-transform duration-300"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                    />
                  </svg>
                  <span className="font-medium">akim42003@gmail.com</span>
                </a>

                <a
                  href="tel:617-659-0691"
                  className="flex items-center space-x-3 text-gray-300 hover:text-blue-400 transition-colors duration-300 group"
                >
                  <svg
                    className="w-5 h-5 group-hover:scale-110 transition-transform duration-300"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                    />
                  </svg>
                  <span className="font-medium">617-659-0691</span>
                </a>

                <a
                  href="https://www.linkedin.com/in/akim42003"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center space-x-3 text-gray-300 hover:text-blue-400 transition-colors duration-300 group"
                >
                  <svg
                    className="w-5 h-5 group-hover:scale-110 transition-transform duration-300"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                  </svg>
                  <span className="font-medium">LinkedIn Profile</span>
                </a>

                <a
                  href="https://github.com/akim42003"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center space-x-3 text-gray-300 hover:text-blue-400 transition-colors duration-300 group"
                >
                  <svg
                    className="w-5 h-5 group-hover:scale-110 transition-transform duration-300"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                  </svg>
                  <span className="font-medium">GitHub Profile</span>
                </a>
              </div>
            </div>
          </div>
        </div>

        <div className="text-center mt-16 pt-8 border-t border-white/10">
          <p className="text-gray-400">© 2024 Alex Kim. Built with React.</p>
        </div>
      </div>
    </div>
  );
};

export default Footer;

// src/lib/components/Footer.svelte
<script>
	const contacts = [
		{ label: 'Email', value: 'akim42003@gmail.com', href: 'mailto:akim42003@gmail.com' },
		{ label: 'Phone', value: '617-659-0691', href: 'tel:617-659-0691' },
		{ label: 'LinkedIn', value: 'linkedin.com/in/akim42003', href: 'https://www.linkedin.com/in/akim42003' },
		{ label: 'GitHub', value: 'github.com/akim42003', href: 'https://github.com/akim42003' }
	];
</script>

<footer class="footer">
	<div class="container">
		<div class="footer-content">
			<div class="contact-section">
				<h3>Contact</h3>
				<p>Feel free to connect or comment about any of my work.</p>
				<ul class="contact-list">
					{#each contacts as contact}
						<li>
							<span class="contact-label">{contact.label}:</span>
							<a href={contact.href} target="_blank" rel="noopener noreferrer">
								{contact.value}
							</a>
						</li>
					{/each}
				</ul>
			</div>
		</div>

		<div class="footer-bottom">
			<p>&copy; 2024 Alex Kim. Built with SvelteKit.</p>
		</div>
	</div>
</footer>

<style>
	.footer {
		border-top: 1px solid var(--color-border);
		margin-top: 3rem;
		padding: 3rem 0 2rem;
	}

	.footer-content {
		margin-bottom: 2rem;
	}

	h3 {
		font-size: 1.1rem;
		font-weight: 600;
		margin-bottom: 0.5rem;
	}

	.contact-section > p {
		color: var(--color-text-muted);
		margin-bottom: 1rem;
	}

	.contact-list {
		list-style: none;
	}

	.contact-list li {
		margin-bottom: 0.5rem;
		font-size: 0.9rem;
	}

	.contact-label {
		color: var(--color-text-muted);
		margin-right: 0.25rem;
	}

	.footer-bottom {
		padding-top: 1.5rem;
		border-top: 1px solid var(--color-border);
	}

	.footer-bottom p {
		color: var(--color-text-muted);
		font-size: 0.85rem;
	}
</style>
